In [1]:
import glob
import sys
import pandas as pd
import numpy as np
import datetime
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
files = "data/"

In [3]:
data_files = glob.glob(files+"/2020-02*.csv.gz")
print(data_files)

['data/2020-02-19.csv.gz', 'data/2020-02-07.csv.gz', 'data/2020-02-15.csv.gz', 'data/2020-02-17.csv.gz', 'data/2020-02-09.csv.gz', 'data/2020-02-05.csv.gz', 'data/2020-02-21.csv.gz', 'data/2020-02-25.csv.gz', 'data/2020-02-29.csv.gz', 'data/2020-02-01.csv.gz', 'data/2020-02-13.csv.gz', 'data/2020-02-27.csv.gz', 'data/2020-02-11.csv.gz', 'data/2020-02-03.csv.gz', 'data/2020-02-22.csv.gz', 'data/2020-02-06.csv.gz', 'data/2020-02-18.csv.gz', 'data/2020-02-14.csv.gz', 'data/2020-02-20.csv.gz', 'data/2020-02-08.csv.gz', 'data/2020-02-16.csv.gz', 'data/2020-02-04.csv.gz', 'data/2020-02-12.csv.gz', 'data/2020-02-24.csv.gz', 'data/2020-02-28.csv.gz', 'data/2020-02-10.csv.gz', 'data/2020-02-02.csv.gz', 'data/2020-02-26.csv.gz']

In [4]:
reqCols = ['TweetID', 'CreatedAt', 'CreatedAt_Full','Hashtags']

In [5]:
df = pd.concat((pd.read_csv(file, usecols=reqCols) for file in data_files), ignore_index=True)
#data for 21-01-2020
df.head()

,CreatedAt,CreatedAt_Full,TweetID,Hashtags
0,2020-02-19,Wed Feb 19 00:00:00 +0000 2020,1229918517673119744,NaN
1,2020-02-19,Wed Feb 19 00:00:00 +0000 2020,1229918518105313281,NaN
2,2020-02-19,Wed Feb 19 00:00:00 +0000 2020,1229918518172356609,'coronavirus'
3,2020-02-19,Wed Feb 19 00:00:00 +0000 2020,1229918518251945984,"'冠状病毒爆发', '冠状病毒', '肺炎', '病毒', '武汉肺炎追踪', '中国', ..."
4,2020-02-19,Wed Feb 19 00:00:00 +0000 2020,1229918518281244673,NaN

In [6]:
df['Date'] = df['CreatedAt']
df.head()

,CreatedAt,CreatedAt_Full,TweetID,Hashtags,Date
0,2020-02-19,Wed Feb 19 00:00:00 +0000 2020,1229918517673119744,NaN,2020-02-19
1,2020-02-19,Wed Feb 19 00:00:00 +0000 2020,1229918518105313281,NaN,2020-02-19
2,2020-02-19,Wed Feb 19 00:00:00 +0000 2020,1229918518172356609,'coronavirus',2020-02-19
3,2020-02-19,Wed Feb 19 00:00:00 +0000 2020,1229918518251945984,"'冠状病毒爆发', '冠状病毒', '肺炎', '病毒', '武汉肺炎追踪', '中国', ...",2020-02-19
4,2020-02-19,Wed Feb 19 00:00:00 +0000 2020,1229918518281244673,NaN,2020-02-19

In [7]:
df['Date'] = pd.to_datetime(df['Date'])
df = df.set_index('Date')
df['Year'] = df.index.year
df['month'] = df.index.month
df['day'] = df.index.day

In [8]:
df.dropna(subset=['Hashtags'], inplace=True)

In [9]:
df.assign(Hashtags=df.Hashtags.str.split(",")).explode('Hashtags')

,CreatedAt,CreatedAt_Full,TweetID,Hashtags,Year,month,day
Date,,,,,,,
2020-02-19,2020-02-19,Wed Feb 19 00:00:00 +0000 2020,1229918518172356609,'coronavirus',2020,2,19
2020-02-19,2020-02-19,Wed Feb 19 00:00:00 +0000 2020,1229918518251945984,'冠状病毒爆发',2020,2,19
2020-02-19,2020-02-19,Wed Feb 19 00:00:00 +0000 2020,1229918518251945984,'冠状病毒',2020,2,19
2020-02-19,2020-02-19,Wed Feb 19 00:00:00 +0000 2020,1229918518251945984,'肺炎',2020,2,19
2020-02-19,2020-02-19,Wed Feb 19 00:00:00 +0000 2020,1229918518251945984,'病毒',2020,2,19
...,...,...,...,...,...,...,...
2020-02-26,2020-02-26,Wed Feb 26 23:49:44 +0000 2020,1232815039305912320,'US',2020,2,26
2020-02-26,2020-02-26,Wed Feb 26 23:49:44 +0000 2020,1232815039305912320,'COVID19',2020,2,26
2020-02-26,2020-02-26,Wed Feb 26 23:49:44 +0000 2020,1232815039444398080,'coronavirususa',2020,2,26
2020-02-26,2020-02-26,Wed Feb 26 23:49:44 +0000 2020,1232815039494660108,'COVIDー19',2020,2,26
2020-02-26,2020-02-26,Wed Feb 26 23:49:44 +0000 2020,1232815039494660108,'ElectScientists',2020,2,26

In [10]:
df['Date'] = df['CreatedAt']
df.head()

,CreatedAt,CreatedAt_Full,TweetID,Hashtags,Year,month,day,Date
Date,,,,,,,,
2020-02-19,2020-02-19,Wed Feb 19 00:00:00 +0000 2020,1229918518172356609,'coronavirus',2020,2,19,2020-02-19
2020-02-19,2020-02-19,Wed Feb 19 00:00:00 +0000 2020,1229918518251945984,"'冠状病毒爆发', '冠状病毒', '肺炎', '病毒', '武汉肺炎追踪', '中国', ...",2020,2,19,2020-02-19
2020-02-19,2020-02-19,Wed Feb 19 00:00:00 +0000 2020,1229918518512115719,"'18Feb', 'Economía', 'China', 'NoticieroVenevi...",2020,2,19,2020-02-19
2020-02-19,2020-02-19,Wed Feb 19 00:00:00 +0000 2020,1229918518600011778,"'Japan', 'coronavirus'",2020,2,19,2020-02-19
2020-02-19,2020-02-19,Wed Feb 19 00:00:00 +0000 2020,1229918518721810433,"'coronavirus', 'animals'",2020,2,19,2020-02-19